variables:
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops
  Drop.Native: $(System.DefaultWorkingDirectory)/xplat
  Llvm.Includes: $(System.DefaultWorkingDirectory)/llvm/include
#   Build.Config: "Release" -> Defined on pipeline.
#   Output.Llvm: "false" -> Defined on pipeline.
#   Build.Llvm: "false" -> Defined on pipeline.

stages:
- stage: Native
  displayName: "Build Native components"
  jobs:
  - job: Build
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
        windows:
          imageName: 'windows-latest'
    pool: 
      vmImage: $(imageName)

    timeoutInMinutes: 240

    steps:
    - pwsh: ./Build-Xplat.ps1
      displayName: 'Run Build-Xplat.ps1 script'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Drop.Native)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/xplat'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Llvm.Includes)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/include'

- stage: Llvm_NET
  displayName: "Build Llvm.NET"
  condition: succeeded()
  jobs:
  - job: Build
    strategy:
      matrix:
        windows:
          imageName: 'windows-latest'
    pool:
      vmImage: $(imageName)

    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/xplat'
        Contents: '**'
        TargetFolder: '$(Drop.Native)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/include'
        Contents: '**'
        TargetFolder: '$(Llvm.Includes)'
    - pwsh: ./Build-Source.ps1
      displayName: 'Run Build-Source.ps1 script'
    - pwsh: ./Invoke-UnitTests.ps1
      displayName: 'Run Invoke-UnitTests.ps1 script'
      condition: succeeded()
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/xplat'
        Contents: '**'
        RemoveSourceFolder: true
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/include'
        Contents: '**'
        RemoveSourceFolder: true

- stage: Publish
  condition: succeededOrFailed()
  jobs:
  - job: Publish
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Ubiquity.NET.Llvm'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: Ubiquity.NET.Llvm
