variables:
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops
  Drop.Native: $(System.DefaultWorkingDirectory)/xplat

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'
  pool: 
    vmImage: $(imageName)

  timeoutInMinutes: 240

  steps:
  - pwsh: ./Build-Source.ps1
    displayName: 'Run Build-Source.ps1 script'
  - pwsh: ./Invoke-UnitTests.ps1
    displayName: 'Run Invoke-UnitTests.ps1 script'
